# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Yws1MDbxu6nMWRVcT2s4-1A573B9GIN

Calculadora com operações : Mutiplicação, Subtração, Adição e Divisão.
"""

# Usuario Digita seu nome e mensagem de saudação
nome = str(input("Olá qual é seu nome ? "))
print(nome,",seja bem vindo a calculadora!")

# Usurario digita dois numeros
print("Vamos começar a fazer operações")
num1 = float(input("Digite o primeiro numero: "))
num2 = float(input("Digite o segundo numero: "))

# Operações
# Mutiplicação
mult = num1 * num2
# Subtração
sub = num1 - num2
# Adição
add = num1 + num2
# Divisão
div = num1 / num2

# Escolher uma operação
print("Muito bem" ,nome," , agora escolha uma operação: ")
# Dicionário com as operações válidas e suas descrições
operacoes = {
    1: "Multiplicação",
    2: "Subtração",
    3: "Adição",
    4: "Divisão"
}

# Exibir as operações disponíveis
print("Operações disponíveis:")
for opcao, descricao in operacoes.items():
    print(f"{opcao}. {descricao}")

# Usuario escolhe uma operação
escolha = int(input("Digite o número da operação desejada: "))

# Validar escolha
while escolha not in operacoes:
    print("Operação inválida. Por favor, escolha uma  número entre 1 e 4.")
    escolha = int(input("Digite o número da operação desejada: "))
#Exbir o resultado da operação
if escolha == 1:
    print(f"Resultado da multiplicação: {mult}")
elif escolha == 2:
    print(f"Resultado da subtração: {sub}")
elif escolha == 3:
    print(f"Resultado da adição: {add}")
elif escolha == 4:
    print(f"Resultado da divisão: {div}")